### ISSUE TITLE
does not support High DPI and multibyte(MFC APP)？

### ISSUE THREAD

**Issue by gzhwl** [jovibor/HexCtrl#37]
Hi, Big Boss:
   I found this perfect Lib, I like to test it, I found it does not support High DPI and multibyte(MFC APP) now, do you have plan to perfect it？[](url)

**Comment by jovibor** [comment]
Hi.
MFC is supported only with **Unicode** charset, multibyte is very obsolete and should not be used for any fresh projects. I have no plans to support it.
As for High DPI, what is exact issue with it? Could you elaborate more?

**Comment by datasynergyuk** [comment]
Multibyte is ancient and modern projects (since the death of Windows 9x at least) shouldn't need it. For what it is worth, it would be huge job to change HexCtrl to work with multibyte. I cannot see it would be practical. That said, if a legacy project is multibyte it would equally be difficult to change that project. In this case, HexCtrl probably isn't suitable. Maybe someone else would like to write a multibyte wrapper for HexCtrl. That would be fun...
